---
abstract: 'Encoding aware Text::CSV.'
author:
  - 'Makamaka Hannyaharamitu, E<lt>makamaka[at]cpan.orgE<gt>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CSV-Encoded
no_index:
  directory:
    - t
    - inc
requires:
  IO::Handle: 0
  Test::Harness: 0
  Test::More: 0
  Text::CSV: 1.31
resources:
  repository: http://github.com/makamaka/Text-CSV-Encoded
version: 0.22
